import { defineConfig } from "tsup";

export default defineConfig({
	entry: {
		index: "src/index.ts",
		"middleware/auth": "src/middleware/auth.ts",
		"middleware/guard": "src/middleware/guard.ts",
		"middleware/logger": "src/middleware/logger.ts",
		"middleware/rate-limit": "src/middleware/rate-limit.ts",
		"middleware/truncate": "src/middleware/truncate.ts",
		"middleware/combine": "src/middleware/combine.ts",
		"middleware/credentials": "src/middleware/credentials.ts",
		"middleware/url-action": "src/middleware/url-action.ts",
		"middleware/oauth": "src/middleware/oauth.ts",
		"middleware/payment": "src/middleware/payment.ts",
		"adapters/stdio": "src/adapters/stdio.ts",
		"adapters/hono": "src/adapters/hono.ts",
		"adapters/express": "src/adapters/express.ts",
		test: "src/test.ts",
	},
	external: ["@modelcontextprotocol/sdk", "zod", "hono", "express"],
	format: ["esm"],
	dts: true,
	clean: true,
	minify: true,
	treeshake: true,
	splitting: true,
	target: "es2022",
	outExtension: () => ({ js: ".mjs" }),
});
